[package]
name = "n-body"
version = "0.1.0"
authors = ["Brandon Mittman <BrandonMittman@gmail.com>"]

[dependencies]
getopts = "*"
clippy = {git = "https://github.com/Manishearth/rust-clippy", optional = true}
