[package]
name = "n-body"
version = "0.1.1"
authors = ["Brandon Mittman <BrandonMittman@gmail.com>"]

[profile.release]
panic = 'abort'

[[bin]]
name = "get-bodies"
path = "src/get-bodies.rs"

[[bin]]
name = "n-body"
path = "src/n-body.rs"

[dependencies]
getopts      = "0.2.*"
serde        = "1.0.*"
serde_derive = "1.0.*"
serde_json   = "1.0.*"
reqwest      = "*"
select       = "*"
regex        = "*"
lazy_static  = "*"
